### ISSUE TITLE
Unable to Send Bitcoins 0.94.1

### ISSUE THREAD

**Issue by mdance** [goatpig/BitcoinArmory#112]
When I attempt to send any amount I get the following error:

There was an error constructing your transaction, due to a quirk in the way Bitcoin transactions work.  If you see this error more than once, try sending your BTC in two or more separate transactions.

It doesn't matter what amount is entered.

**Comment by mdance** [comment]
Clicking under Coin Control, there is one address listed as a Change Address containing the full balance

**Comment by achow101** [comment]
You will probably want to do a full rebuild and rescan of the databases. Also, upgrading to 0.95.1 probably wouldn't hurt.

**Comment by mdance** [comment]
I just installed 0.95.1, and am now receiving the following error:

(ERROR) BDM.py:184 - DB error: DB version mismatch. Use another dbdir!

Armory then prompts that its going to close

**Comment by achow101** [comment]
Find the armory datadir and delete the folder named "databases". Then try again.

**Comment by martysto** [comment]
Probably off topic but deleting the datadir isn't always helpful. I can reproduce this as well and remember dealing with this some time ago. The ERR "DB version mismatch. Use another dbdir!" is misleading.

Here is what I observed:
§0 bitcoind and armory have a different understanding of the blockchain when in comes to consistency.
§1 Process in the background keeps running after armory shuts down. Kill it manually: `/usr/bin/ArmoryDB`, otherwise changes will not be noticed.
§2 Armory scans the blockchain (e.g.: `.bitcoin/blocks`) during startup and throws an exception while bitcoind ignores invalid files. 
(1) I had some blk*.dat files with zero size probably due to some crash of bitcoind at some point earlier.
(2) Find potential faulty files: `ls -l | awk '{if ($5 == 0) print $9}'`
(3) Since Armory 0.95, renaming won't help, you have to remove every file that contains non-valid blockchain data.
