### ISSUE TITLE
Selected wallet becomes unselected after a while

### ISSUE THREAD

**Issue by AndySchroder** [goatpig/BitcoinArmory#124]
Under "available wallets", if one selects a wallet and waits for a while with armory running, after a while no wallets will be selected any more. The selected wallet should remain selected until armory is closed and reopened.

**Comment by goatpig** [comment]
That's the wallet ledger redrawing on new blocks.

**Comment by AndySchroder** [comment]
I believe that the selected transaction is also forgotten after a while too. The wallet ledger may be re-drawing on new blocks, but this forgetfulness of it is a nuisance. Other types of programs like my e-mail client don't forget what I have selected, just because that list pane is updating. I think this is going to cause a lot of frustration for users.

**Comment by achow101** [comment]
I wouldn't call it a nuisance. Blocks only happen every 10 blocks, certainly not frequent enough for it to become "a nuisance". Both ledgers need to be redrawn so that the new transactions, transaction confirmations, and balance are updated. The fix is pretty simple; we just need to cache the selections.
