### ISSUE TITLE
version 0.95.1 not available for arm/rpi

### ISSUE THREAD

**Issue by joernroeder** [goatpig/BitcoinArmory#162]
Hey,
i'm currently setting up another raspberry pi to interact with a bitcoin 0.13 full node and was wondering why the latest version isn't available on the download page for armhf.

**Comment by goatpig** [comment]
ARMs and RPis are x86. Armory's DB code does not support x86 anymore (since 0.93).

RPi builds are only provided to use as offline signers, and currently 0.92 is the last version with wallet changes, meaning it can sign transactions created by all following versions. Therefor, there is no reason to put out a RPi build for the current software.

**Comment by joernroeder** [comment]
All right. Thanks for the explanation.

**Comment by 4oo4** [comment]
If the older offline installs for Raspberry Pi will still work with transactions generated by newer versions, that's totally OK, but I was just wondering if it's still the case that there's no x86 Armory? I was kinda confused when I saw this on the Releases page of btcarmory.com but didn't see an RPi/offline build when 0.96.1 was released:

> Due to some build system and dependency issues, MacOS, Raspberry Pi, and Offline binaries will not be available for this release. These will be released shortly with 0.96.1 which will fix those issues on those platforms as well as a few other bug fixes that were recently reported.

https://btcarmory.com/0.96.0-release/

**Comment by goatpig** [comment]
Will release offline and Pi builds for 0.96.2

**Comment by 4oo4** [comment]
@goatpig 

Awesome, thanks!

**Comment by 4oo4** [comment]
@goatpig This issue came up again when I was trying to get my offline wallet updated to a version that would let me claim BCH from my wallet, and I can see that there are only i386/amd64 builds for the offline version. 

Is it correct that there won't be any armhf builds going forward (and that it's also impossible to build yourself)? I attempted to cross compile 0.96.3 for armhf, but the build kept failing at the ArmoryDB part (which isn't a surprise from what you said above). I still really want to use Armory as a cold storage wallet, and wanted to know more about Armory and architectures before I go buying a non-ARM single board PC.
