### ISSUE TITLE
Support lightweight mode

### ISSUE THREAD

**Issue by fresheneesz** [goatpig/BitcoinArmory#174]
I don't want to have to download the entire blockchain these days. But Armory is the only client I've found that takes security seriously. I can't use armory because it takes DAYS to DL the blockchain before I can use it, and I can't use any other system because they're fucking amateurs. Armory lightweight mode please!

Look how multibit ignores their security fail: keepkey/multibit-hd#952 (comment)

**Comment by fresheneesz** [comment]
Some additional conversation: https://github.com/etotheipi/BitcoinArmory/issues/332

**Comment by goatpig** [comment]
The notion of lightweight is not well defined.

For all intents and purposes Armory can operate according the same framework as "lightweight" wallets since 0.95

In this case a lightweight wallet means a bare GUI that interfaces with a block data server remotely. Since 0.95, the client and server have been split in 2 stand alone binaries, that communicate with each other over a socket.

This is necessary to fulfill your purpose, but I'd argue not sufficient in most scenarios. Indeed this setup does not protect your privacy nor encrypts the communication channel.

The current state of Armory only allows you to interface a client with a trusted remote server, over a trusted network. This is a feature currently targeted at power users and business. 

Its purpose is to avoid the need to replicate blockchain and DB data per terminal within a LAN, and allow low spec devices to only operate a lean GUI instead of the full stack (phones, low power laptops, old desktops).

Currently if you have a powerful machine at your disposal with a good connection, you could setup a Bitcoin full node and ArmoryDB on that system, and connect the client remotely to that server over a socket.

Development plans relevant to your case include:

- Blocks over P2P. This will allow to split the DB and the node. The DB currently needs disk access to the node's blockchain data.

- BIP151 style encryption and an added certificate based authentication layer. Bitcoin Core is moving to this style of encryption + auth on top of the node P2P protocol. Armory will need this implementation to interface with remote nodes once blocks over P2P is there, so the code will also be leveraged for client-server communications.

- Supernode database, which will allow arbitrary block data look up.

Even with these improvements, there are a few things you can't expect out of this stack:

- You shouldn't try to connect to an untrusted node. Armory trusts its underlying node for valid blockchain data. Modifying this premise requires implementing at least part of the consensus layer in Armory, which I will not do.

- I will not run any "official" Armory supernode servers. I do not intent to compete with lightweight wallets' on that front, nor do I have the resources to do this. Armory is one of the rare fullnode stack, it is meant to be used that way. 

You can either setup a system of your own where you split db and client (you can do this atm), or trust another party for the DB service (you should wait for encryption and auth layers first).

- If you do not own the DB service, you are leaking privacy to whoever is.

**Comment by fresheneesz** [comment]
Thanks for the detailed info.

"the consensus layer"

Could you elaborate on what consensus layer you're talking about? 

For me personally, I'm not concerned with privacy. If I wanted that, I'd use tor and bitcoin mixers. I am concerned with security and good solid backups, which Armory does really well. Even using a malicious server node, the worst-case scenario is A. accepting someone's double spend or B. not having your payment sent out to the actual blockchain, right? A only applies if you're a merchant, and B is a minor inconvenience, not a breach of security.

**Comment by achow101** [comment]
> Could you elaborate on what consensus layer you're talking about?

The Consensus Layer means checking that all blocks and transactions are valid according to the consensus rules. Armory relies on a local Bitcoin Core node to do this and thus that node is trusted and must be trusted. Armory will not check the validity of blocks and transactions by itself.

> Even using a malicious server node, the worst-case scenario is A. accepting someone's double spend or B. not having your payment sent out to the actual blockchain, right? A only applies if you're a merchant, and B is a minor inconvenience, not a breach of security.

Actually connecting to a malicious server node means that the attacker could feed you bad data. They could lead you to believe that you have more or less Bitcoin than you really do. They can have you on a fork of the blockchain so you aren't really connected to the Bitcoin network. It would mostly be an inconvenience, but it could be a rather major inconvenience.

**Comment by fresheneesz** [comment]
"The Consensus Layer means checking that all blocks and transactions are valid according to the consensus rules."

Is there somewhere I can read more about "the consensus rules"? Is this a specific standard or a more general concept?

"It would mostly be an inconvenience, but it could be a rather major inconvenience."

Agreed on all points. These are all things I would be perfectly fine with as a trade off for much more convenience. I'd be curious if other Armory users hold the same stance.

**Comment by achow101** [comment]
> Is there somewhere I can read more about "the consensus rules"? Is this a specific standard or a more general concept?

It is a specific standard that is specified by the code of the reference implementation, Bitcoin Core. They are fairly well documented, but keep in mind that the code is the spec, not the documentation (weird, I know, basically legacy from Satoshi). There's documentation on [bitcoin.org](https://bitcoin.org/en/developer-documentation) and the [bitcoin wiki](https://en.bitcoin.it/wiki/Protocol_documentation) which describes the consensus rules.

> I'd be curious if other Armory users hold the same stance.

That's a question suitable for the [forums](https://bitcointalk.org/index.php?board=97.0), you can make a thread there and ask.

**Comment by fresheneesz** [comment]
Thanks I'll do that. But man this forum is pretty unusable. I can only search once every 1.5 minutes, and it wouldn't let me post, telling me that I already posted within the last 6 minutes... I checked my profile and that wasn't true. These are pretty absurd limits. Am I missing something about how to use this forum properly?

**Comment by achow101** [comment]
The forum has very strict restrictions on new members to prevent people from making new accounts and spamming. If you post stuff, those restrictions will be lifted after a week or two. The posting thing is actually  any action like attempting to post (timer resets if you do) and searching (I think)

**Comment by fresheneesz** [comment]
Ah ok. Thanks

**Comment by fresheneesz** [comment]
Gah, now that it saved my post as a draft, I don't see a way to post my draft. And I can't post it again, cause it recognizes that it matches my draft. And now I can't even *find* my drafts. Jesus H Roosevelt Christ

**Comment by fresheneesz** [comment]
I'm sorry, that forum is absolutely unusable. I give up on trying to post there. I would very much appreciate if someone could it for me, or better yet, start using a forum that isn't absolutely garbage.
