### ISSUE TITLE
tx broadcast timed out (send)

### ISSUE THREAD

**Issue by Horsebeaver** [goatpig/BitcoinArmory#243]
I've been trying to send out BTC for the past few days. Im getting the error "tx broadcast timed out (send)" every single time. I've also tried to adjust the fee's but the issue still remains.

Please help

Using armory 0.96-beta-a3d01aa722

**Comment by goatpig** [comment]
Wait for the next testing build, sometimes tonight.

**Comment by Horsebeaver** [comment]
Cheers! The "tx broadcast timed out (send)" message seems to have gone away and been replaced by "bad-txns-inputs-spent". Any ideas?

**Comment by achow101** [comment]
That means that the inputs of the transaction you are creating have already been spent. That means that you are attempting to create a double spend. If you experienced a "tx broadcast timed out (get)" error before, then this will happen since the node will have accepted the original transaction but Armory not known that that had happened. Then when you tried to send again, Armory reused the same inputs since it doesn't know that they were spent.

**Comment by Horsebeaver** [comment]
Ah, I must have emptied my whole balance throughout the past few days. Kinda sucks, but what can you do.
Thanks for the rapid response and help :)
