### ISSUE TITLE
linux build instructions are outdated

### ISSUE THREAD

**Issue by vrs** [goatpig/BitcoinArmory#270]
I tried to use https://github.com/goatpig/BitcoinArmory/blob/master/linuxbuild/Linux_build_notes.md, but it seems the build has been migrated to autotools in the meantime. What are the current build instructions?

**Comment by goatpig** [comment]
A) Setting up the repo
1) git clone https://github.com/goatpig/BitcoinArmory.git
2) Checkout the branch you want to build (usually master, dev, testing or a given tag).
3) git submodule init
4) git submodule update

B) Building
1) make sure autotools and libtool are installed
2) sh autogen.sh
3) ./configure
4) The configure script may fail, 99% of the time it's because you are missing a package, which it will name. Install the missing package and rerun configure.
5) make -jX (where X is the number of threads on your CPU).
6) sudo make install

**Comment by achow101** [comment]
#255 updates the instructions

**Comment by goatpig** [comment]
merged
