### ISSUE TITLE
"Coin selection failed with error: failed to select utxos" when sending max

### ISSUE THREAD

**Issue by fresheneesz** [goatpig/BitcoinArmory#285]
It seems Armory has an edge case where if you click "MAX" when trying to send, then select a higher fee, it gives you the above error when trying to send or previewing the transaction. This actually first happened to me *before* I messed with the fee for some reason - no idea why that might be. But users are 99% of the time going to do any fee changing *after* they've selected the amount to send, and so changing the fee should automatically change the amount sending if necessary (possibly with a message to the user about it).

**Comment by goatpig** [comment]
It's a button, not a checkbox. Buttons are no binding. If you change a parameter, you need to press the button again for the effect to take place again.

I change the button to checkbox and made it binding since people want it that way, but at no point was this a bug.

https://github.com/goatpig/BitcoinArmory/blob/testing/changelog.txt#L6

**Comment by fresheneesz** [comment]
Well, don't you see how that's incredibly confusing? I mean, first of all, I could take plenty issue with "checkboxes are binding, buttons aren't", but regardless, this isn't a good user experience. Its not intuitive, it doesn't make sense, it doesn't help the user figure out how to fix the problem. 

It almost sounds like you're taking this personally. I'm not trying to say "its a bug, you're the worst programmer". I'm just trying to say, this could be improved...

**Comment by goatpig** [comment]
This feature has been so since Armory is Armory. I have not received complaints about this up until the implementation satoshi/Byte fee calculation. 

A button is a button. I don't understand what there is to be confused about, but I've delivered the change since undeniably people are getting confused.

And yes, it does frustrate to have to spend time on a GUI element that users do not understand even though it is semantically correct.

**Comment by fresheneesz** [comment]
I'm sure you can appreciate that "its always been that way" is an absolutely terrible excuse for a UI decision (or any decision). Thank you for taking my (and I guess, other's) feedback seriously. I do have to disagree with you that the UI as it is (was) makes sense. If in any case, a user can perform an action and not either get an expected correct response, OR an understandable error message that informs a user what to do instead, that is a UI problem (whether you want to call it a bug or not). 

I'm a programmer that prides myself in being very good at coming up with intuitive, good UIs and APIs, and I totally understand the feeling that someone should have read the fucking manual, but please continue to take people's feedback to heart. Setting aside your biases in coming up with a UI that works for most people is of utmost importance in designing a good UI. I've learned that, its impossible to have proper perspective from just my own point of view.
