### ISSUE TITLE
Build instructions on Arch are broken

### ISSUE THREAD

**Issue by stevenroose** [goatpig/BitcoinArmory#286]
The AUR package that is mentioned has a dependency on the `twister` package that does not exist.

**Comment by UncleHunto** [comment]
The AUR package "armory-git" has not been updated for some time, and will only work up to version 0.95.  the "twisted" dependency in Arch is now named "python2-twisted", but this dependency is no longer needed in versions 0.96.0 and higher. If you would like to build and install the most recent stable version (0.96.1) on an Arch based system, I would suggest trying my "armory-goatpig-git" AUR package.  Note that on Arch, with 0.96.1, there is a bug where after using the "coin control" menu once to create a transaction, it will cause Armory to freeze if you try to use the "coin control" menu again. This bug is fixed in the latest version of the testing repo (not in the 0.96.2 RC2 binary). If you wish to install the testing version (do so at your own risk, of course) you may do so by editing the "armory-goatpig-git" PKGBUILD before installation, and adding "#branch=testing" (without the quotes) at the end of the "source" address. continue building the package, and it will install the latest version from testing. Again, do so at your own risk ;-)

**Comment by stevenroose** [comment]
Thanks, will try some time :) I'm trying to see if there is still money on a paper Armory backup that I made some time ago. I don't have it near, so I will only test again in some weeks/months. 

There is no tool that converts an (maybe deprecated) Armory style backup into BIP 39 seed mnemonic? I guess the HD structure was different back then.

**Comment by UncleHunto** [comment]
I do not know of a tool which would convert an Armory backup into a BIP 39 seed mnemonic. I don't think Armory's wallet uses the same structure as BIP 39, so this might not be possible.  BTW that coin control bug I mentioned appears to have been something specific to my wallet, and which I have since resolved, so isn't something you need to worry about with your wallet.

**Comment by goatpig** [comment]
There is no way to convert an Armory seeds to BIP39.

**Comment by laCour** [comment]
@stevenroose I've updated the `armory-git` AUR package to resolve this.
