### ISSUE TITLE
How to enable RPC in Armory 0.96.1

### ISSUE THREAD

**Issue by MerrekSK** [goatpig/BitcoinArmory#294]
Hi, thanks for closing my last issue so promptly.

Of course, upgrading to Armory 0.96.1 did not help at all. I have figured out that I need to enable RPC. Thanks for pointing that out, really.

How to do that? I created the bitcoin.conf file with server=1, ran bitcoinid to ensure the conf file is valid (I used a sample .conf file that had a few uncommented lines), ran armory and it is still PURPLE meaning no RPC.

Any manual on this would be appreciated. This is my last attempt with Armory, I have been using it for almost 3 years. If this does not work, I am done with it.

Cheers,
M.

**Comment by goatpig** [comment]
Try the RC: 

https://github.com/goatpig/BitcoinArmory/releases/tag/v0.96.1.2

If you need help enabling your node RPC, you need to ask the node devs. Im going to close this because this page is for actual issues, reported by people with sufficient technical chops to help narrow it down. 

What you are experiencing is benign and you will have a much better time asking help from the community on the forums: 

https://bitcointalk.org/index.php?board=97.0
