### ISSUE TITLE
Impossible to send bitcoins from Armory Wallet for few weeks

### ISSUE THREAD

**Issue by patrick-faure** [goatpig/BitcoinArmory#306]
Each time I want to send bitcoins from my Armory Wallet, I have a "Tx Broadcast Time out (Send)" message, with the possibility that it is because my fee is not enough high. The first time I tried with the default fee but now I multiplied it by around x1000 and it is still the same. 
I have no possibility to use my bitcoins for weeks as it is stuck in my Armory Wallet. Please kindly help me.
[armorylog_20170907_2309.txt](https://github.com/goatpig/BitcoinArmory/files/1286144/armorylog_20170907_2309.txt)
[armorylog_20170907_2309.txt](https://github.com/goatpig/BitcoinArmory/files/1286145/armorylog_20170907_2309.txt)

![image](https://user-images.githubusercontent.com/4282581/30185154-a63ceefe-9420-11e7-9e17-305dadfcd498.png)

**Comment by goatpig** [comment]
Use the forums for this kind of stuff:

https://bitcointalk.org/index.php?board=97.0

**Comment by patrick-faure** [comment]
Hello,
I don't understand why it was closed. If you simply read the display box, it is written to attach a support ticket here. It is an development issue and I respected the rules written by the developper.

**Comment by goatpig** [comment]
Your issue is known and benign. Most likely, you didn't update. I don't have enough time to handle case by case issues of this nature, and there if forum where people will be happy to assist you with basic setup.

This is stuff the average user can help you with. You do not need time from the main and only full time developer (i.e. me) for this kind of issue. If you had updated, you would have not seen that message to begin with.

**Comment by patrick-faure** [comment]
Many thanks and good luck for the future developments. I will post on the forum next time.
