### ISSUE TITLE
extra address generation

### ISSUE THREAD

**Issue by tril0byte** [goatpig/BitcoinArmory#357]
I set my default address type to P2SH-P2WPKH in settings, and click Receive Bitcoins. I copy the address to the clipboard and hit Done, then go to Unused Addresses > P2SH-P2WPKH and it has added the one I copied, plus 1 extra. This happens each time I click Receive Bitcoins.

**Comment by tril0byte** [comment]
happens in both 0.96.2 and 0.96.3.99

**Comment by david-yam** [comment]
By the way, I recalled that there was an "Generate Addresses" button with an user input form to specify the number of extra addresses to be generated.   

This function is now missing in 0.96.2 and 0.96.3. How can I operate on the addresses which have a very large index (e.g. > 100), instead of generating them back one by one?

**Comment by goatpig** [comment]
It's there, you need to be Expert User mode to see it.

**Comment by tril0byte** [comment]
the extra addresses are at Index+100 of the one I just generated
