### ISSUE TITLE
Menu bar bug macOS

### ISSUE THREAD

**Issue by dffffffff** [goatpig/BitcoinArmory#380]
Macbook Air 6,2
macOS 10.13.1 (17B1003)
Armory 0.96.3.99.-beta 

Menu bar is unresponsive if any dialogue besides the main UI is open.

Steps to reproduce 
Run Armory.app
Open any dialogue window. For instance Settings, Wallet properties etc.
In the menu bar, try to access any of the options; Show Armory (if tabbed to another app or Finder), Send Bitcoins, Receive Bitcoins, Quit Armory.
Observe that they are unresponsive.

**Comment by droark** [comment]
Hi. I can't reproduce this issue. Can you run Armory from the terminal (/*Armory.app location*/Armory.app/Contents/MacOS/Armory) and report what happens on the terminal when you try to click the options?

Thanks.

**Comment by droark** [comment]
Okay. I have managed to reproduce it. I'll look into it but I'm not sure that there's much I can do about it. Long story short, Armory has some "technical debt" from when it was first built. Because of this and an unfinished attempt at cleaning things up (very long story), Armory relies on a critical library that's no longer supported by the developer. If the problem is with how Armory uses the library, this might be fixable. If not, no dice.

Thanks.
