### ISSUE TITLE
Please sign git tags

### ISSUE THREAD

**Issue by josephbisch** [goatpig/BitcoinArmory#40]
Please sign the git tags with a PGP key. Alan did so for the older tags, but I noticed when checking v0.94.1 that it doesn't appear to be signed. This is helpful for downstream packagers, like Linux distros and in general for anyone downloading the source code instead of binaries. Without signing, GitHub must be trusted.

Due to the nature of this software, I think it is risky for Linux distros to package Armory without signed tags. I'm going to hold off on packaging newer versions of Armory in Debian until tags are signed.

Thanks!

**Comment by goatpig** [comment]
Will look into it. I need to figure out how to do this offline, as my GPG private key is on a air gapped device.

**Comment by josephbisch** [comment]
I'm not sure how best to do it. Maybe use a livecd without networking enabled and put the key on that along with the repo and sign it and bring the repo with the signed tag back to a computer with internet access somehow? Not convenient, but it doesn't need to be done that often if just for tags.

Thanks.

**Comment by goatpig** [comment]
For now I'm thinking to pull the repo into a usb key, take it my air gapped machine, tag and sign there, then take it back to my online machine and push from there.

**Comment by AndySchroder** [comment]
That sounds like it would be one step better than what is happening at the moment at least. I guess there is no "tag signing request" that can be done it git? If so, maybe there isn't anything better you can do anyway?

**Comment by AndySchroder** [comment]
Also, has there been any effort to utilize gitian for builds/packages?

**Comment by goatpig** [comment]
> Also, has there been any effort to utilize gitian for builds/packages?

That's a long story actually. Armory relies too much on Python as is to ease Gitian support. 

I plan on splitting the code base into stand alone libraries (each in their own repo) and approach deterministic building incrementally instead.

**Comment by AndySchroder** [comment]
Also, I made a similar post about a month ago: https://www.reddit.com/r/Bitcoin/comments/4ibjk2/requesting_community_feedback_on_armory_0941_by/

One thing not addressed in this current discussion that is mentioned in my above link is the authenticity of the key being used to sign tags and releases in the first place. It might be a little boost of confidence if Alan Reiner ("etotheipi") would sign your PGP key with the one he used on his previous git tag signatures. I'm not sure what your relationship is whether this would be possible though. Alan's announcements of his halted efforts and your continuation were not cryptographically signed in any way.

**Comment by goatpig** [comment]
If Alan still has that key he would sign mine. Signing tags is one thing (it's a reasonable request). 

Asking for the previous lead to cryptographically prove he passed the torch over to me is no different from superstition. The best you are getting is the illusion of security. Appeal to authority is a poor and dangerous basis for evaluating code. Just read it instead.

What value does it provide to know Alan signed my key if he has not and will no review any of the new code? What if he had sold that key to someone else like another wallet developer did recently? What if the UN had a GPG key and offered to sign mine. Would that make you feel safer? What artifact do you favor the most?

Deterministic builds with a quorum of signatures is actually a step forward in the quality and security of the project. This is something I will work towards. Signed tags are useful addition as well.

Getting a one time signature from a friend is a waste of everybody's time at best. I'm not going down that path unless you can develop an argument in its favor.

> Alan's announcements of his halted efforts and your continuation were not cryptographically signed in any way.

Again, such a signature has no value. It's no different from giving me a blank check, it carries no guarantees as to how I will spend it. 

Imagine ATI had instead decided to go full closed source. I would have forked Alan's repo and forwarded development on my own. Now instead of getting a forum post about how Alan is passing the project over to me, you would get one announcing how I am a rogue developer and you shouldn't trust me. What would you do then? Take your chances with the closed source software? Or review my code?

What would be valuable is for Alan to review and sign my releases, but that's not going to happen.

**Comment by AndySchroder** [comment]
Thank you for the very rational comments. I wasn't trying to say that Alan Reiner was an almighty power that can authorize your work, just that "it might be a little boost of confidence".

I think any signature of a GPG key's fingerprint can help, not hurt. How much help a signature provides can vary dramatically based on the situation. There is a bit of a lack of a "web of trust" for your key, and that is the issue I'm trying to address.

You are right, reviewing source code and locally compiling is the end all solution to trust issues. Everyone in the world can't mentally process every source code change to every piece of software that they use. That's the point of commit signing, deterministic builds, and a web of trust. It provides a balance, while still giving one the option to do different levels of verification that suit their desire.

**Comment by AndySchroder** [comment]
What are the issues with gitian exactly? The fact that python and all the python dependencies that one may already have installed and rely on aren't actually covered by the gitian process? Or, can gitian not include uncompiled data in its result?

**Comment by goatpig** [comment]
Ask Joseph, he dealt with that in depth. I just remember that Python (PyQt) and SWIG (binding C++ code for Python) complicated the task. 

It should otherwise be fairly easy to use Gitian to spit out deterministic builds of pure C++ code. I'd rather break down the code base into stand alone libs to master Gitian over a smaller, simpler project.

I do intent to move the makefiles/msvs projects to cmake. That should make the process easier across the board.

**Comment by goatpig** [comment]
> Thank you for the very rational comments. I wasn't trying to say that Alan Reiner was an almighty power that can authorize your work, just that "it might be a little boost of confidence".

I think any signature of a GPG key's fingerprint can help, not hurt. How much help a signature provides can vary dramatically based on the situation. There is a bit of a lack of a "web of trust" for your key, and that is the issue I'm trying to address.

I was writing a response to that and somehow never posted it.

I understand the benefit of a web of trust. However Alan has exited this space, and even though he has contributed a lot to the community, is a one time signature from his key with no reviewing and expertize attached really all that valuable?

If people would review my new code and offer to sign my key afterwards, I'd gladly take that. I can get Alan's sig but I don't see the point. I also want to avoid developing a culture of authority.

You don't trust me? That's actually a good thing, trust isn't something that should be bestowed lightly. As a start, you can review my development history and contributions to this project. Then you can offer suggestions as to how to improve the process. Signed tags is a good suggestion. Getting Alan's cryptographic voucher, meh.

At this point, asking Alan to sign my key has more to do with belief than trust. Trust implies verification. He doesn't have to time to go over my new code. He didn't go over the stuff I wrote for 0.93 and ATI's 0.94 to begin with.

Web of trusts are valuable only if they are used as intended. If Gandhi/Obama/Darth Vader/*insert celeb of your choice* signed my key, what value would it really provide?

Proper vouching would be for the current users that do review and run my code to sign my key. Ideally, they would just get to run Gitian and sign the build hashes.

**Comment by josephbisch** [comment]
I can't easily reference the exact issues with gitian builds of Armory right now, but building Python related dependencies such as PyQt and Python itself proved particularly difficult. I forget exactly why, but I remember that there were issues that could only be resolved by switching to Python 3 and PyQt5 instead of Python 2 and PyQt4. We could have potentially used Python binaries as supplied by the Python Software Foundation for instance, but I feel that using prebuilt binaries of non-reproducible software defeats the purpose of going through the whole gitian process and should be avoided if possible. Of course the operating system itself (that you run as the host and in the gitian VM) along with all its packages are non-reproducible. Hopefully that will change before too long, but Debian and others are actually working on changing that. More recently I have added Debian guest support to the gitian tools in anticipation of Debian eventually becoming fully reproducible. The Tor Project recently released a version of Tor Browser Bundle that uses Debian Wheezy vms for gitian builds (for other reasons because Debian isn't reproducible yet).

There were also challenges associated with making the OS X app and the Windows exe from Linux (gitian uses Linux vms), let alone make those reproducibly. I was using a PyQt tool that freezes a PyQt app.

In any case I think modularizing Armory is a good idea.

**Comment by goatpig** [comment]
Is this discussion over? Right now tags are signed with the same key I use for offline signing the releases. 

I'm open to suggestions. Keep in mind that end game is to  have at least gitian support for mission critical crypto code.

**Comment by josephbisch** [comment]
Yeah, I'm closing this now.
