### ISSUE TITLE
Need Help...your help

### ISSUE THREAD

**Issue by scottjack791** [goatpig/BitcoinArmory#475]
I know you referred me to the help site to get my problems resolved, but I can't post unless I donate Bitcoin.  I can't donate Bitcoin unless I get Armory to open.
I need you to help me...please.  I have tried deleting and reinstalling Armory.  I've updated bitcoin core.  I have updated Armory with the latest version you sent me.  Why won't it run.  I had no problem until I decided I wanted to send it.
Now it won't even open.  The Armory DB gets an error.
I need to know what to do from you PLEASE.  I NEED to send this Bitcoin ASAP.  Now I have even lost money because Bitcoin has gone down.
Please help me!  I know you think I'm an idiot...maybe I am when it comes to computers, but help me and you'll never hear from me again.  LOL!!

**Comment by droark** [comment]
Can you please explain why, on multiple occasions, you've ignored our directions? Why are you not posting in the forum that was posted in at least two of the issues you posted? If anything, ignoring our directions and continually opening new issues just makes us less inclined to help.

**Comment by 4oo4** [comment]
@scottjack791 It sounds like running Armory is over your head, it's probably time for you to switch to a different wallet, especially if you're that desperate to get access to your coins.

http://docs.bitshares.org/muse/migration/howto-exporting-wallet-clients.html

**Comment by scottjack791** [comment]
Hello,
Yes, I agree.  Thank you for that link, but I can't access my keys because I can't get Armory to open.  I have my Passphrase and my Root Key to bring back my wallet.  How can I get my "Private Key Code"

How can I get Armory to open?  Again, It keeps saying that ArmoryDB isn't responding and ArmoryQt.exe is not responding.
I will follow any and all instructions you give me.  What should I do????

I'm so sorry to be a pain in your ass, but trust me, as soon as I get my Bitcoin out of Armory, I promise not to bother you
In order to "sweep" my keys I need my "private key code".   I need to get Armory to open to get this information so I can sweep my keys.
If you give me more information in your emails I can better follow what you want me to do.
Thank you!

**Comment by droark** [comment]
> I will follow any and all instructions you give me.  What should I do????

With all due respect, I'm not going to help. This comment was the final straw. You've been told on multiple occasions to move over to the Armory subforum on bitcointalk.org. You've refused to do so. Instead, you keep opening issues here, even after goatpig closes your issues. I'm going to assume you're not that concerned about your coins if you're ignoring the explicit requests of the developers to move to a different forum *filled with people who are able to help*. If you can't follow the most basic instructions regarding where to seek help, I can only assume that trying to talk you through your problem is going to be like pulling teeth, and will be a huge time sink while goatpig & I work to get the next version of Armory ready.

I don't mean to be harsh. I really don't. I just don't have the patience to handle people who stubbornly refuse to follow simple directions, at least not without explaining why they refuse to follow such directions. (I think you said something about having trouble logging in but never explained further. If that's the problem , you need to explain what's going on, and do a Google search first to see if there's a solution.) bitcointalk.org and IRC are the primary venues for people who need help troubleshooting. It'd be nice if more people were here but they aren't. The other two are your best bets for getting help.

**Comment by 4oo4** [comment]
@scottjack791 Run Armory in offline mode and you should be able to get to the wallet properties and export the keys. Also, in the future you should heed @droark's advice on how to get help, frantically opening issue after issue and totally disregarding what people are asking you to (do to help them help you) is extremely disrespectful and counterproductive.

**Comment by scottjack791** [comment]
I'm sorry, but please read this message clearly.  I did take his advise about going to bitcointalk.org. but I could not post because it was requiring me to pay Bitcoin in order to do so.  I told him this and he insisted i wasn't following his instructions.  I simply asked him if there was another way or if he could please assist me.  His answer was I'm sorry, but I'm busy working on code for Armory.  I updated Armory as he recommended (about 10 times) and he just kept telling me to update Armory!  Trust me, I'm listening to you guys, I need you to listen to me.

Here is the deal.  I would love to open Armory in offline mode, but as I said in my last few posts, Armory WILL NOT OPEN in any mode.  I'm trying to get someone to simply tell me how I can re-set it or do anything to get it to open.  Every time I attempt to open Armory I get this message "ArmoryQt.exe is not responding".  What does that mean???
I need to do something to get it to respond so It will open Armory.  Then I can follow your advise about sweeping the keys.
I promise never to bother you guys again after I get this fixed, but I will ask once again...How can I get ArmoryQt.exe to respond?  I can't open Armory.
Thank you.  Sorry for being a pain in your asses.

**Comment by droark** [comment]
> I did take his advise about going to bitcointalk.org. but I could not post because it was requiring me to pay Bitcoin in order to do so.  I told him this and he insisted i wasn't following his instructions.

I just created a throwaway account from a coffee shop. I didn't need to pay anything to gain access. If it's insisting that you pay, I suggest you take your laptop to a coffee shop, open an incognito window in your browser of choice, and create another account. If you don't have a laptop, go to your local library and create an account. If all else fails and you truly have no choice but to pay some coins, set up a throwaway wallet on Robinhood/Gemini/Coinbase/wherever, buy some coins, and pay.

> Here is the deal.  I would love to open Armory in offline mode, but as I said in my last few posts, Armory WILL NOT OPEN in any mode.

If you really installed 0.96.4 RC3 and it won't open, something is seriously wrong with your computer. You deleted something you shouldn't have deleted, or there's a bigger problem. Either way, I'm not helping with that, period. (I've tried in the past and spent hours walking people through the most basic steps of operating a computer. Never again.) If someone else will, cool. Chances are somebody will help on the forum. Whether or not your coins are important enough to start working on gaining access to the forum is a question only you can answer.

**Comment by scottjack791** [comment]
Douglas, Good for you,you're good with computers.  You probably went to university to learnabout this, but not everyone did.  Guess what, I'm your customer, andright now, your customer relation skills are in need of some training.  I'd appreciate if you would dial down your attitude and do your job.  By the way, that job if you are unaware is to take care of your customers.  No matter how much of a pain in the ass they might be to you.
 I followed yourlink to the "updated" version, but when you get to the site it is not0.96.4 RC3,  it says it is 0.96.3 RC3.  Does that make adifference?  I don't know.
 Listen man, I've attached 2 screen shots of what I'm getting when I try to open Armory.  I have tried uninstalling and reinstalling Armory numerous times including updating it with the link you provided.  I've also uninstalled Bitcoin Core and reinstalled it as well.

I'm hoping you can try to ignore the pain this causes you and try to help me.  Yes, I tried to go to the coffee shop to create a username for your "help site" and it did the same thing.  Pay or you can't post.  I'm not going to buy more Bitcoin just to have access to a help website.  I'm in China (US Citizen) and it is not easy to buy Bitcoin with RMB.
I don't care what you have to do or how much time it takes you.  Help me get through this with YOUR product.  Look at these pictures I've attached.  Armory will not open past this point.
Thank you Douglas,

**Comment by goatpig** [comment]
> Guess what, I'm your customer, andright now, your customer relation skills are in need of some training.

I'm the boss around these parts.

You are no customer of mine. You are using free open source software. No one pays for Armory. Nobody contributing code for Armory has an obligations to you or any Armory users. I do this out of my free time, with no compensation, for 3 years now. 

What ground do you stand on that believe you are entitled  to demand anything out of me or any other contributor to this project?

> I'd appreciate if you would dial down your attitude and do your job.

Apply this logic to yourself then. Again, no one here is paid to help anybody. This is an issue page for people with enough technical skills to at least help with the debugging. 

You have been instructed to create a forum account and log in there. This is a thread I just created out of a brand new throw away account as proof that there is no barrier of entry to this forum:

https://bitcointalk.org/index.php?topic=3117351.0

Yet, you are polluting this page with your pleas for hand-holding over benign setup issues. How do you expect us developers to react to this? You are lucky you are even being engaged with at this point.

If I hand hand hold over this issue page, I am opening the flood gates to needy and abusive unskilled users of your kind to directly nag and waste the time of our developers. I will certainly not tolerate this. The forum has plenty of patient and helpful people waiting to go over your case, step by step. The only part required of you is to go there and lay out your story. Stop disappointing!

**Comment by droark** [comment]
Pretty much what goatpig said. I've done the whole handhold-clueless-users-through-everything job before. It's a horrific pain in the butt. If you want to lecture me about what I do in my free time while demanding help, open up your wallet. (Spoiler alert: I'm not cheap!) I don't mind when people are really trying and just need a little boost, or if they've found a bug. I do mind when I'm expected to do basic tech support and cater to somebody's every whim.

Since you claim to be in China - information that would've been helpful to have long ago instead of repeatedly begging for help and ignoring our directions - what I'll do is give you the login credentials for my throwaway account if you give me an email address. At that point, you're on your own. Having trouble buying BTC? Go to a local Bitcoin meetup, or arrange to have a friend outside China pay the bill, or whatever. Be creative! Bluntly stated, your complete and utter lack of desire to solve this problem on your own, combined with your entitled attitude, implies to me that whoever does end up helping is going to have their work cut out for them.

Finally, if you're going to get snarky, can you at least be accurate? Please tell me where exactly on [this page](https://github.com/goatpig/BitcoinArmory/releases) it says 0.96.**3** RC3. I'll wait.
