### ISSUE TITLE
Paper Backup and SecurePrint 0.96.4

### ISSUE THREAD

**Issue by CryptoSigmund** [goatpig/BitcoinArmory#527]
Dear Developer,
dear Community,

I just created a new wallet with version 0.96.4-beta-fee1f91a31 and tried the Single-Sheet (Unencrypted) and Single-Sheet (SecurePrint) - and the secure print didn't pass the restore test. Checked it again several times.

Can anybody confirm this issue?

Sincerely yours with best wishes, Freud.

**Comment by droark** [comment]
Hi. Thanks for the report. Can you please post your logs?

**Comment by goatpig** [comment]
Hi,
Thanks for the bug report. I can confirm the issue on Windows 10 x64. From my investigations, this only affects AES CBC decryption with optimized builds of CryptoPP with the most recent MSVC compiler, i.e. the backup is valid but fails to decrypt correclty.

I'm still investigating the extend to which CryptoPP is producing bogus results with these MSVC updates. So far nothing else has showed up yet. 

Only SecurePrint uses CBC mode, other parts of the code all use CFB, which is unaffected. Baring any new discovery, since the issue only affects decryption of SecurePrint backups, and the backups are otherwise sound, I'll simply push the fix to the testing branch as part of the upcoming 0.96.5 bugfix release. 

Prior versions of Armory should be able to decrypt these backups in the meantime. As per the nature of the issue, it only affects Windows.

**Comment by goatpig** [comment]
Hi,
Thanks for the bug report. I can confirm the issue on Windows 10 x64. From my investigations, this only affects AES CBC decryption with optimized builds of CryptoPP with the most recent MSVC compiler, i.e. the backup is valid but fails to decrypt correclty.

I'm still investigating the extend to which CryptoPP is producing bogus results with these MSVC updates. So far nothing else has showed up yet. 

Only SecurePrint uses CBC mode, other parts of the code all use CFB, which is unaffected. Baring any new discovery, since the issue only affects decryption of SecurePrint backups, and the backups are otherwise sound, I'll simply push the fix to the testing branch as part of the upcoming 0.96.5 bugfix release. 

Prior versions of Armory should be able to decrypt these backups in the meantime. As per the nature of the issue, it only affects Windows.

**Comment by goatpig** [comment]
After review, this issue only affects Windows builds of 0.96.4. It has been fixed here: 6d1bbb62521dd87c80e58a2057dd41f90251e07d
