### ISSUE TITLE
Armory 0.96.5 does not open on MacOS 10.14.2

### ISSUE THREAD

**Issue by dpeim2029** [goatpig/BitcoinArmory#551]
I just installed most recent version of Armory from www.btcarmory.com but I can´t open it, same message as other user reported earlier: "Check with the developer to make sure Armory works with this version of macOS. You may need to reinstall the application. Be sure to install any available updates for the application and macOS."

What´s the issue? Or how can I use Armory?

**Comment by droark** [comment]
Hi. I just downloaded the latest version and was able to run it on 10.14.2. Where is Armory located? I have it in /Applications.

**Comment by droark** [comment]
@dpeim2016 - Any updates?

**Comment by luomijie** [comment]
I can't open any version of release version in my mac os Mojave 10.14.5. Can you give me a hard?

**Comment by luomijie** [comment]
I can't open any version of release in my mac os Mojave 10.14.5. Can you give me a hard?

**Comment by luomijie** [comment]
I can't open any version of release in my mac os Mojave 10.14.5. Can anyone  give me a hard?

**Comment by luomijie** [comment]
I can't open any version of release on my mac os Mojave 10.14.5. Can anyone give me a hard?

**Comment by droark** [comment]
@luomijie - Hi. Did you place Armory in `/Applications`?

**Comment by luomijie** [comment]
> @luomijie - Hi. Did you place Armory in `/Applications`?

Yeah ,I have placed Armory in my /Applications .

**Comment by luomijie** [comment]
this link can't open https://github.com/goatpig/BitcoinArmory/blob/master/osxbuild/OSX_build_notes.md.

**Comment by droark** [comment]
@luomijie - You want to use [this link](https://github.com/goatpig/BitcoinArmory/blob/master/osxbuild/macOS_build_notes.md). Also, what exactly happens when you attempt to run Armory? Do you get some sort of error message? What happens if you go into the terminal, go to `/Applications/Armory.app/Contents/MacOS`, and run `./Armory`?

**Comment by luomijie** [comment]
@droark Thank you for your help ,I go to /Applications/Armory.app/Contents/MacOS, and run ./Armory the Armory is Running offline mode successfully.

**Comment by raspulton** [comment]
Hi Guys, 

do you know if Armory 0.96.5 can be installed on macOS 10.14.6 ? 

I followed the steps on https://github.com/goatpig/BitcoinArmory/blob/master/README_macOS.md to verify the download file and install it, but many things didn`t work out:

- After step 1 being successful, Step 2 in the guide says: „If everything is successful, execute the following command: "brew install openssl“  -  Here I get „command not found“ - What can I do about this?
<img width="901" alt="Screenshot 2019-09-13_3" src="https://user-images.githubusercontent.com/54560585/64846644-b6d1d780-d63f-11e9-9aef-dda9b260b26b.png">

- Continuing successfully until step 5, here it says „Verify the SHA-256 hash of the macOS build.“  The only feedback I get here is a square bracket open to the left side, but no confirmation.


- At step 6 „Verify that the SHA-256 hash list was actually signed by goatpig.“  I receive the message „No such file or directory“ and in the second row „verify signature failed: No such file or directory“
<img width="1108" alt="Screenshot 2019-09-13_4" src="https://user-images.githubusercontent.com/54560585/64846736-f4366500-d63f-11e9-9bfc-d50ef8471558.png">

- Next thing I did was using OpenPGP to verify armory_0.96.5_osx.tar.gz by using the „Verify Signature of File“ option. This gave me the message: „Verification FAILED:No Signatures found.“
<img width="1153" alt="Screenshot 2019-09-13_1" src="https://user-images.githubusercontent.com/54560585/64846769-06180800-d640-11e9-8b81-252b8d9fb4b0.png">

- Last thing I did: Install it anyways. After running, it immediately displayed a huge error message saying: „Armory cannot be opened because of a problem. Check with the developer to make sure armory works with this version of macOS. You may need to reinstall the application“  etc. 
<img width="952" alt="Screenshot 2019-09-13_2" src="https://user-images.githubusercontent.com/54560585/64846799-1af49b80-d640-11e9-8814-7e6139a20a4e.png">

Is there anything I can do to make the latest version of Armory run on a current macOS 10.14.6?

Thank you guys in advance!
