### ISSUE TITLE
Cannot send BTC transactions out. Multiple attempts at different fees, all timed out.

### ISSUE THREAD

**Issue by Von-Tito** [goatpig/BitcoinArmory#646]
Ok what the hell, I am on block chain looking at transactions being processed for 52 sat/B. 52!!! Not 500 to 1000 as it seems to take to get Armory to send a god damn transaction. If this is how your company is goin to handle BTC I would like to move all my crypto to another wallet as that is robbery and I will not stand for it. Please rectify your broken fee system ASAP or I will be closing all accounts and wallets associated with this program.

**Comment by MCM-Mike** [comment]
From my experience, Armory in Expert mode has the ability to choose the `tx fee` by yourself. So you can set the fee as you wish. 
Perhaps you can share a bit more insight on your actions what you did when your `tx` did time out?

As we all know `Armory` is not easy to use wallet, but it was never designed that way. Therefore when using it you have to have some understanding and make sure your `BTC-Node` is up and full synced and all other prerequisites to run Armory.

**Comment by goatpig** [comment]
There are no accounts nor a profit model in Armory. You have never paid for this software because this option simply does not exist.

Armory fees are fetched as is from Core. The Bitcoin Core fee logic is built on what it has seen of the mempool. It cannot use mined transactions to guess fees since some transactions are mined "out-of-band". Therefor the longer you let your Bitcoin Core node run, the more accurate a fee estimate it will get.

As mentioned previously, you can manually set fees in expert mode. The automated fee feature is only there for users who do not want to optimize fees on their own.

The timeout logic is based on the P2P layer, it has nothing to do with the attached fee. If Armory reports a timeout, it does not mean the transaction has not been broadcasted. It means Armory has tried and failed to fetch your own node's mempool for the broadcasted transaction. This is not a deterministic indication that the transaction won't enter the mempool.

You can copy the raw hex transaction from Armory and broadcasted it directly from Bitcoin-Qt instead.
