### ISSUE TITLE
Armory Stuck on node offline

### ISSUE THREAD

**Issue by elbaulp** [goatpig/BitcoinArmory#662]
I have a wallet which I am trying to recover, but I am facing lots of problems.

- On windows, I'm stuck on `node offline` Bitcoin is already synced.
- It was impossible to install armory on Macos, even trying some PRs that are there to support openssl1.1
- On Linux (gentoo) lots of problems with pyqt4

Is there any plan to solve this situation? Is there anything in which I could try to help?

**Comment by goatpig** [comment]
> Is there any plan to solve this situation?
WIP in the dev branch.

> On Linux (gentoo) lots of problems with pyqt4
Ubuntu 18 VM is your solution on Linux atm. Other chroot to install pyqt4 and python2. Do not try to install pyqt4 for py3, 0.96.5 only runs on py2.

> It was impossible to install armory on Macos, even trying some PRs that are there to support openssl1.1
Dev branch is py3 and qt5 (pysides2) so all issues there should be gone. It also doesn't need to expose any C++ libs to python so that should ease the build snafu.

> On windows, I'm stuck on node offline Bitcoin is already synced.
Most likely a pathing or port clash issue, ask on the community forums: https://bitcointalk.org/index.php?board=97.0

> Is there anything in which I could try to help?
Still in the process of migrating qt4 to pysides2 if you wanna help on that front.

**Comment by elbaulp** [comment]
Thanks, will try the solutions you mentioned
