### ISSUE TITLE
Dependency is not satisfiable: python (>= 2.6)

### ISSUE THREAD

**Issue by DocMors** [goatpig/BitcoinArmory#689]
Hi, this is on an out of the box Ubuntu 22.04 and applies to all 0.95 and 0.96 versions I've tried. I'm somewhat stuck finding a solution, due to each of the search terms being used in so many articles it's hard to find something related. I suspect this has come up before, could someone please point me to the relevant issue? Thanks Mike

**Comment by goatpig** [comment]
Ubuntu since 20.04 (I believe) doesn't ship with python2 anymore.

There's work in the dev branch to update Armory to python3 and qt5. It isn't user friendly yet. You choices are:
- downgrade to an older Ubuntu (or run it in a VM)
- try your chances with the dev branch
- wait for the new version (no ETAs, sorry)

**Comment by DocMors** [comment]
Thanks a mil. Still got a 18.04 VM :)
